assets:
  settings.xml: cqfn/secrets#settings.xml
  pubring.gpg: cqfn/secrets#pubring.gpg
  secring.gpg: cqfn/secrets#secring.gpg
install: |
  pdd --file=/dev/null
merge:
  script: |
    LC_ALL=C mvn clean install -Pqulice --errors -Dstyle.color=never
release:
  script: |-
    mvn versions:set "-DnewVersion=${tag}" -Dstyle.color=never
    git commit -am "${tag}"
    sed -i "s/0\.0\.0/${tag}/g" $(find . -name '*.eo')
    mvn clean install -Dinvoker.skip
    mvn clean deploy -Pcqfn -Psonatype --errors --settings ../settings.xml -Dstyle.color=never

    cp eo-parser/src/main/resources/XMIR.xsd /tmp
    branch=$(git rev-parse --abbrev-ref HEAD)
    git checkout gh-pages
    git reset --hard
    sudo /bin/bash -c "cd '$(pwd)'; git clean -fd"
    cp /tmp/XMIR.xsd .
    sed -i "s|SNAPSHOT|${tag}|" XMIR.xsd
    git add XMIR.xsd
    git commit -am "${tag}"
    git checkout "${branch}"
