language: java
sudo: false
cache:
  directories:
    - $HOME/.m2
script:
  - set -e
  - mvn clean install -Pqulice --errors --batch-mode
  - mvn clean
env:
  global:
    - MAVEN_OPTS="-Xmx256m"
    - JAVA_OPTS="-Xmx256m"
install:
  - gem install pdd -v 0.20.5
  - gem install est
  - gem install xcop
jdk:
  - oraclejdk8
