---
name: codecov
on:
  push:
    branches:
      - master
concurrency:
  group: codecov-${{ github.ref }}
  cancel-in-progress: true
jobs:
  codecov:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: teatimeguest/setup-texlive-action@v3.0.0
        with:
          update-all-packages: true
          packages: scheme-basic geometry xcolor naive-ebnf microtype etoolbox
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-
      - run: mvn install -Pjacoco
      - uses: codecov/codecov-action@v4
        with:
          files: ./eo-parser/target/site/jacoco/jacoco.xml,./eo-runtime/target/site/jacoco/jacoco.xml,./eo-maven-plugin/target/site/jacoco/jacoco.xml
          fail_ci_if_error: true
