name: daily
on:
  schedule:
    # Run load testing at 01:30 UTC every day
    - cron: '30 1 * * *'
jobs:
  build:
    runs-on: [ ubuntu-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v3
      - run: |
          # Make script runnable
          chmod +x "${GITHUB_WORKSPACE}/scrips/test-repetition.sh"
          # Test eo-parser
          bash "${GITHUB_WORKSPACE}/scrips/test-repetition.sh --max 10 --folder ${GITHUB_WORKSPACE}/eo-parser"
          # Test eo-maven-plugin
          bash "${GITHUB_WORKSPACE}/scrips/test-repetition.sh --max 10 --folder ${GITHUB_WORKSPACE}/eo-maven-plugin"
          # Test eo-runtime
          bash "${GITHUB_WORKSPACE}/scrips/test-repetition.sh --max 10 --folder ${GITHUB_WORKSPACE}/eo-runtime"
          

