name: daily
on:
  schedule:
    # Run load testing at 01:30 UTC every day
    - cron: '30 1 * * *'
  pull_request:
    branches:
      - master
    paths-ignore: [ 'paper/**', 'sandbox/**' ]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-jdk-${{ matrix.java }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-jdk-${{ matrix.java }}-maven-
      - run: |
          SCRIPT="${GITHUB_WORKSPACE}/src/test/scripts/test-repetition.sh"
          # Check that script is exists
          if [ ! -f "${SCRIPT}" ]; then
              echo "Script ${SCRIPT} not found"
              exit 1
          fi
          # Make script runnable
          chmod +x "${SCRIPT}"
          # Test eo-parser
          ${SCRIPT} --max 10 --folder ${GITHUB_WORKSPACE}/eo-parser
          # Test eo-maven-plugin
          ${SCRIPT} --max 10 --folder ${GITHUB_WORKSPACE}/eo-maven-plugin
          # Test eo-runtime
          ${SCRIPT} --max 10 --folder ${GITHUB_WORKSPACE}/eo-runtime
      # @todo #2085:90min Add GitHub action step to create an issue.
      #  It would be convenient to add github action step that will create an
      #  issue in case of any of the tests is failed. We can do it through
      #  <a href="https://github.com/JasonEtco/create-an-issue">create-an-issue</a>
      #  action. Also, you can read about that problem in that discussion:
      #  <a href="https://github.com/orgs/community/discussions/25111">
      #  Create an issue case the workflow fails</a>

