---
name: ebnf
on:
  push:
    branches:
      - master
    paths-ignore: ['paper/**', 'sandbox/**']
concurrency:
  group: ebnf-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ebnf:
    runs-on: ubuntu-20.04
    env:
      CONVERT_PATH: /tmp/antlr4-to-bnf-converter
    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo apt-get update
          sudo apt-get -y install ghostscript imagemagick texlive-extra-utils pdf2svg
      - uses: teatimeguest/setup-texlive-action@v2.6.2
        with:
          update-all-packages: true
          packages: scheme-basic geometry xcolor naive-ebnf microtype etoolbox
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-jdk-${{ matrix.java }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-jdk-${{ matrix.java }}-maven-
      - run: |
          mkdir -p $CONVERT_PATH
          wget --quiet http://public.yegor256.com/convert.zip -O /tmp/convert.zip
          unzip -o -d $CONVERT_PATH /tmp/convert.zip
      - run: mvn clean test '-P!jacoco' -Dtest=XMIRTest -pl :eo-parser --errors --batch-mode --quiet
      - run: sudo sed -i '/disable ghostscript format types/,+6d' /etc/ImageMagick-6/policy.xml
      - run: |
          cp eo-parser/src/test/resources/tex/ebnf.tex eo-parser/target/ebnf.tex
          cd eo-parser/target
          sed -i -e '/EBNF/{r ebnf.txt' -e 'd}' ebnf.tex
          pdflatex -shell-escape -interaction=errorstopmode -halt-on-error ebnf.tex
          pdfcrop --margins '10 10 10 10' ebnf.pdf crop.pdf
          pdf2svg crop.pdf ebnf.svg
          convert -density 300 -quality 100 -transparent white -colorspace RGB crop.pdf ebnf.png
          mkdir gh-pages
          cp ebnf.png gh-pages
          cp ebnf.svg gh-pages
      - uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: gh-pages
          folder: eo-parser/target/gh-pages
          clean: false
        if: github.ref == 'refs/heads/master'
