name: latexmk
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: yegor256/latexmk-action@0.2.1
        with:
          path: paper
          opts: -pdf eolang-paper
          packages: acmart
