---
name: linters
on:
  push:
    branches:
      - master
    paths-ignore: ['paper/**', 'sandbox/**']
  pull_request:
    branches:
      - master
    paths-ignore: ['paper/**', 'sandbox/**']
jobs:
  qulice:
    name: Qulice
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - run: |
          gem install xcop
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: mvn -P qulice clean install -DskipTests=true -DskipITs=true --errors --batch-mode

  pdd-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: g4s8/pdd-action@master
