---
name: loc-badge
on:
  push:
    branches:
      - master
concurrency:
  group: loc-badge-${{ github.ref }}
  cancel-in-progress: true
jobs:
  loc-badge:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
      - uses: shadowmoose/GHA-LoC-Badge@1.0.0
        with:
          debug: true
          directory: .
          badge: target/loc-badge.svg
      - uses: JamesIves/github-pages-deploy-action@v4.6.0
        with:
          branch: gh-pages
          folder: target
          clean: false
        if: github.ref == 'refs/heads/master'
