---
name: sonar
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths-ignore: [ 'paper/**', 'sandbox/**' ]
concurrency:
  group: sonar-${{ github.ref }}
  cancel-in-progress: true
jobs:
  sonar:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: teatimeguest/setup-texlive-action@v3.0.2
        with:
          update-all-packages: true
          packages: scheme-basic geometry xcolor naive-ebnf microtype etoolbox
      - uses: actions/setup-java@v4
        with:
          java-version: 20
          distribution: 'temurin'
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - env:
          CONVERT_PATH: /tmp/antlr4-to-bnf-converter
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn install -Pjacoco --batch-mode --errors && mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.qualitygate.wait=true --batch-mode --errors
