---

name: typos
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  typos:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: crate-ci/typos@master
